# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmarc', '0006_auto_20160408_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='source_ip',
            field=models.CharField(max_length=39),
        ),
    ]
