# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-08 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmarc', '0007_auto_20161121_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True)),
                ('source_ip', models.CharField(max_length=39)),
                ('domain', models.CharField(max_length=100)),
                ('email_from', models.CharField(blank=True, max_length=100)),
                ('email_subject', models.CharField(blank=True, max_length=100)),
                ('spf_alignment', models.CharField(blank=True, max_length=10)),
                ('dkim_alignment', models.CharField(blank=True, max_length=10)),
                ('dmarc_result', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('email_source', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FBReporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100, unique=True, verbose_name=b'Organisation')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='fbreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmarc.FBReporter'),
        ),
    ]
